### ISSUE TITLE
Container Stats Fails

### ISSUE THREAD

**Issue by MwC-Trexx** [hassio-addons/addon-portainer#3] opened 2018-09-17 00:36 UTC
# Problem/Motivation

STATS function is broken

## Expected behavior

Showing Container CPU/Memory Stats

## Actual behavior

Get Error Message: **Error running ps: exit status 1**

## Steps to reproduce

Point to container, and click stats icon.

**Comment by frenck** [comment] 2018-11-19 22:49
Please do not mark this stale my friend bot

**Comment by TonyApuzzo** [comment] 2018-11-23 06:46
I have the same problem.

New user of portainer, clicked on stats tab and got error as above.  No stats shown.

Plain install of HASSIO 0.82

**Comment by tarbax** [comment] 2019-01-06 14:45
same problem here.
latest hassio (resinos) on intel nuc

**Comment by turricansi** [comment] 2019-01-22 17:05
i have the same problem

**Comment by tboyce021** [comment] 2019-03-20 17:16
Mine tells me

```
ps: ps: invalid option -- 'e'
```

**Comment by frenck** [comment] 2019-04-01 18:36
Works in upcoming version:

![image](https://user-images.githubusercontent.com/195327/55351047-b09ad500-54bd-11e9-8ed2-b47770befdfe.png)

![image](https://user-images.githubusercontent.com/195327/55351091-c14b4b00-54bd-11e9-8243-311e4b35d577.png)

**Comment by tboyce021** [comment] 2019-04-01 20:34
Should this work in 0.5.0? I just tried and still get the same error.

**Comment by frenck** [comment] 2019-04-01 20:34
it should, as per screenshots above.

Could you please provide me with your system details? (shown in the startup of the add-on, in the logs).

**Comment by frenck** [comment] 2019-04-01 20:35
re-opening issue to see what @tboyce021 comes up with.

**Comment by tboyce021** [comment] 2019-04-01 20:42
Mine is actually probably a HassOS issue. I just thought to try it on the host itself and get the same `ps: ps: invalid option -- 'e'` error from `docker top homeassistant`. Here is my info though:

```
 Add-on version: 0.5.0
 You are running the latest version of this add-on.
 System: HassOS 2.11  (amd64 / qemux86-64)
 Home Assistant version: 0.90.2
 Supervisor version: 152
```

**Comment by lweberru** [comment] 2019-04-02 10:55
still don't work with 0.5.0 (same error as before)

**Comment by lweberru** [comment] 2019-04-02 11:35
Here what I get logging into portainer itself via console:

```
root@a0d7b954-portainer:/$ /opt/portainer/docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                           NAMES
e806381245dd        hassioaddons/portainer-armv7               "/init"                  6 hours ago         Up 6 hours          0.0.0.0:9000->9000/tcp                                           addon_a0d7b954_portainer
eb3b6e69c037        homeassistant/armhf-hassio-supervisor      "python3 -m hassio"      13 hours ago        Up 13 hours                                           hassos_supervisor
20927f2427b7        hassioaddons/ssh-armv7                     "/init"                  7 days ago          Up 7 days                                           addon_a0d7b954_ssh
5eb193cb226e        hassioaddons/mqtt                          "/init"                  7 days ago          Up 7 days           0.0.0.0:1883-1884->1883-1884/tcp, 0.0.0.0:4883-4884->4883-4884/tcp, 0.0.0.0:5713->5713/tcp   addon_a0d7b954_mqtt
5371162416eb        homeassistant/raspberrypi3-homeassistant   "/bin/entry.sh pytho…"   8 days ago          Up 8 days                                           homeassistant
78285007e64a        hassioaddons/node-red-armv7                "/init"                  9 days ago          Up 9 days                                           addon_a0d7b954_nodered
45470316462e        homeassistant/armv7-addon-configurator     "/run.sh"                3 weeks ago         Up 3 weeks          0.0.0.0:3218->3218/tcp                                           addon_core_configurator
befdcc6f06ea        homeassistant/armv7-addon-samba            "/run.sh"                3 weeks ago         Up 3 weeks                                           addon_core_samba
5b76919e33b2        netdata/netdata                            "/usr/sbin/run.sh"       2 months ago        Up 2 weeks          0.0.0.0:19999->19999/tcp                                           netdata
root@a0d7b954-portainer:/$ /opt/portainer/docker top 5371162416eb
Error response from daemon: Error running ps: exit status 1
root@a0d7b954-portainer:/$
```

**Comment by frenck** [comment] 2019-04-02 11:58
Makes sense, the daemon does this on the host level, so this indicates the `ps` command on the host is more limited. Probably caused by busybox, which runs on HassOS, which has more limited functionality compared to the GNU version.

**Comment by tboyce021** [comment] 2019-04-05 11:54
Sounds like this isn't going to be fixed on HassOS. Is there a way to make Portainer use the HassOS API or is this just going to remain broken for HassOS?

**Comment by tboyce021** [comment] 2019-04-05 12:25
I'm not sure the HassOS API is sufficient for this anyway. I only see a way to get stats for HA and add-ons, but I don't see a way to get stats for any container installed outside of that (i.e. using Portainer itself).

**Comment by tomlut** [comment] 2019-05-02 03:07
Any idea who we could ask in the dev team about adding the ps command to HassOS?

This is a valuable tool for tracking down excessive resource use.

**Comment by TonyApuzzo** [comment] 2019-05-02 17:06
HassOS uses [buildroot](https://buildroot.org/) to configure the system.  It should be a relatively simple matter of tracking down which buildroot package contains the full `ps` and friends and adding it to a configuration file and rebuilding HassOS.  If there is already a ps linked to busybox then will have figure out how to not have them conflict.

I may have some time this weekend to do a sample build of HassOS and see if that addresses this issue.  

Disclaimer, I'm not a core dev and have little to no influence.  But, if it works I will create a pull-request and see if it is accepted.

**Comment by tboyce021** [comment] 2019-05-02 17:20
FYI, it does have `ps` but it comes from busybox and doesn't support the `-e` flag that Portainer apparently uses.

**Comment by TonyApuzzo** [comment] 2019-05-04 05:44
I built the work-in-progress HassOS dev branch (3.1) with PROCPS_NG enabled and that does seem to fix portainer stats:

![image](https://user-images.githubusercontent.com/341037/57174498-41d2d380-6dfd-11e9-966b-2b0bef2e8eef.png)

I will create a PR in HassOS and see if it goes anywhere.

**Comment by TonyApuzzo** [comment] 2019-05-07 16:37
The pull request with the fix was accepted into the dev branch for HassOS 3.1 -- I do not know how long it will be before the 3.x branch goes live for general users, but it will eventually be in the base.

**Comment by lweberru** [comment] 2019-05-13 14:35
Just updated HASSOS to Release 2.12. And now it is really working. Well done!

**Comment by tomlut** [comment] 2019-05-13 14:53
Confirmed. Nicely done.

**Comment by frenck** [comment] 2019-05-13 17:34
Nice! Closing issue! 👍

**Closed by frenck** 2019-05-13 17:34 UTC
