### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by snelweg** [hassio-addons/addon-portainer#5] opened 2018-10-06 14:12 UTC
Installes on HASSIO: parse error: Expected string key before ':' at line 1, column 4

 Hass.io Add-on: Portainer v0.2.0
 Manage your Docker environment with ease
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 1.11 / HA 0.79.3 / SU 133 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-docker.sh: executing... 
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
[cont-init.d] 11-docker.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

**Comment by frenck** [comment] 2018-10-06 14:12
Duplicate of #4

**Closed** 2018-10-06 14:13 UTC
Labels: Closed: Duplicate
